name: "Custom Slack Action"
description: "Send a fully custom slack notification"
inputs:
  template:
    description: "slack message json template file"
    required: true
runs:
  using: "node12"
  main: "index.js"
branding:
  color: blue
  icon: send
