name: "Custom Slack Action"
description: "Send a fully custom slack notification"
inputs:
  template:
    description: "slack message json template file"
    required: true
  color:
    description: "color of slack message"
    required: false
  title:
    description: "slack message title"
    required: false
  summary:
    description: "test execution summary"
    required: false
  report_url:
    description: "test report url"
    required: false
  report_path:
    description: "test report path"
    required: false
  datadog_query:
    description: "datadog url"
    required: false
  commit_authors:
    description: "commit authors"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: blue
  icon: send
